# Generated by Django 5.2.4 on 2025-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Format: #RRGGBB', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'clothes'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='users_imgs'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('xl', 'X-Large'), ('xxl', 'XX-Large'), ('xxxl', 'XXX-Large')], max_length=5),
        ),
        migrations.AddField(
            model_name='clothes',
            name='available_colors',
            field=models.ManyToManyField(blank=True, help_text='Select available colors for this item', to='MALAZ.color'),
        ),
    ]
