# Generated by Django 5.2.4 on 2025-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0002_color_alter_clothes_options_alter_clothes_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='available_colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
