# Generated by Django 5.1.4 on 2025-07-05 17:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0003_remove_clothes_available_colors_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('orange', 'Orange'), ('gray', 'Gray'), ('brown', 'Brown'), ('cyan', 'Cyan'), ('gold', 'Gold'), ('silver', 'Silver'), ('navy', 'Navy Blue'), ('maroon', 'Maroon'), ('teal', 'Teal'), ('olive', 'Olive Green')], max_length=20, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='clothes_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='clothes',
            name='colors',
            field=models.ManyToManyField(blank=True, to='MALAZ.color', verbose_name='Available Colors'),
        ),
    ]
