# Generated by Django 5.1.4 on 2025-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0004_color_alter_clothes_options_clothes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='colors',
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'clothes'},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='users_imgs'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
