# Generated by Django 5.1.4 on 2025-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0005_remove_clothes_colors_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='available_colors',
            field=models.CharField(blank=True, help_text='Enter available colors separated by commas (e.g. Red, Blue, Black)', max_length=255),
        ),
    ]
