# Generated by Django 5.1.4 on 2025-07-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0006_clothes_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='available_colors',
            field=models.CharField(help_text='Enter available colors separated by commas (e.g. Red, Blue, Black)', max_length=255),
        ),
    ]
