# Generated by Django 5.1.5 on 2025-07-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0010_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='available_colors',
        ),
    ]
