# Generated by Django 5.2.4 on 2025-07-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0011_remove_clothes_available_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
