# Generated by Django 5.2.4 on 2025-07-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0013_rename_added_at_cartitem_created_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
