# Generated by Django 5.2.4 on 2025-07-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MALAZ', '0014_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
